sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-extra-utils latex-xcolor pgf
script:
  - pdflatex -interaction=nonstopmode -halt-on-error hydra-architecture-diagram.tex
  - latex    -interaction=nonstopmode -halt-on-error hydra-architecture-diagram.tex
  - dvisvgm --no-fonts hydra-architecture-diagram.dvi hydra-architecture-diagram.svg
after_success:
  - ./.travis_build_pages.sh
